# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build Status

on:
  push:
    branches: [ "AA-CCBS" ]
  pull_request:
    branches: [ "AA-CCBS" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Boost Library
        run: sudo apt-get install libboost-all-dev
      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make
